### ISSUE TITLE
Save issue with re-imported Data Exports

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#101]
### Describe the bug
Clicking Save when editing an advanced Profile will not close the advanced editor, you have to click cancel. The updated timestamp in Manage Profiles shows the Profile had been updated but if you re-edit the profile nothing has changed.

### To Reproduce
1. Import this profile - [Aeldari-v1.2.txt](https://github.com/user-attachments/files/16359276/Aeldari-v1.2.txt)
2. Go to **Manage Profiles**
3. Search for `Striking Scorpions x5`
4. Click **Edit**
5. Expand the `Striking Scorpions x5` Unit.
6. Click **Preset Abilities**.
7. Select a random ability from the list
8. Click **Save**
9. See Save not closing result.
10. Click **Cancel**.
11. See the Timestamp has changed next to `Striking Scorpions x5`
12. Click **Edit**
13. Expand the `Striking Scorpions x5` Unit.
14. See the **Unit abilities** section is empty.

### Expected behavior
It would save correctly.

### Additional context
If i import the current [Aeldari-v1.1.txt](https://github.com/korzxd/UnitCrunch-data-exports/blob/main/Factions/Aeldari/Aeldari-v1.1.txt) i can convert those basic profiles to advanced profiles, follow the same steps as above and it works fine.

So it was working when i started creating this export but in that time i've Exported and Imported this Data Export due to working on it across 2 different machines both running the same OS and using the same Browser and maybe the error has occurred somewhere in that process.

**Comment by dixhuit** [comment]
Thanks for the bug report. Will investigate ASAP.

**Comment by dixhuit** [comment]
Just tried to recreate and I get a console error at step #7. I wonder if that's the cause or is at least related. Will fix that first and take it from there.
