### ISSUE TITLE
Add "on an objective" as a condition for the defender

### ISSUE THREAD

**Issue by Grizzlea** [dixhuit/unitcrunch-issue-tracker#104]
A number of abilities (Necron Immortals, Rubric Marines to name two) have conditional effects based on being on an objective. Could we add it as a condition, similar to 'defender within cover' or 'within half range', and trigger effects on it?

**Comment by dixhuit** [comment]
I think the simplest solution to this and similar conditions is to just toggle the modifier on/off to simulate being on or off the objective.
