### ISSUE TITLE
Whitelist the "Psychic attack" condition so it's available in combination with more effects & conditions

### ISSUE THREAD

**Issue by Grizzlea** [dixhuit/unitcrunch-issue-tracker#105]
In particular, would like to create the Thousand Sons Detachment rule, which is either Lethal Hits, Sustained Hits or Dev Wounds if attack is Psychic.

At the moment, you can't condition on attack step roll modifier with psychic, and so have to put the buff on the weapons themselves (which can't be toggled on/off).

**Comment by dixhuit** [comment]
Sounds like we just need to make the "Psychic attack" condition available in more instances (whitelist for use with more effects and other conditions). Will investigate ASAP but this sounds reasonable, thanks for the suggestion!
