### ISSUE TITLE
Blast is not adding attacks properly when there are multiple model types 

### ISSUE THREAD

**Issue by KerniusMaximus** [dixhuit/unitcrunch-issue-tracker#107]
### Debug data
You can send debugging data to help with diagnosing the issue. Just set up a simulation that recreates the issue and then submit the form at: https://www.unitcrunch.com/send-debug-data

### Describe the bug
When using advanced profiles on a defender to have multiple model types, an Attacker with a BLAST weapon is not properly totaling up the number of models in the unit to add additional attacks. I have attached screenshots of an example with a weapon that has d6+1 attacks and BLAST. The defender has one model type that has 4 models and one model type with 1 model. This adds up to 5 models and BLAST should add one to the attack value. 

### To Reproduce
1. Create an Attacker with a weapon with the BLAST keyword
2. Create a Defender with multiple unit types that each individually are less than 5, but add up to 5. 
3. Run a simulation 

### Expected behavior
I expect the defenders models to be summed up before blast logic is applied. With the example above, I expect to see 3.5+1 attacks from the base weapon profile and 1 additional from BLAST, for a total of 5.5 attacks. In the screenshot you can see that it shows only 4.5.

### Screenshots
![Screenshot_20240812-163923](https://github.com/user-attachments/assets/c2da661f-a8f3-403b-b9e5-33cd56e11bdf)
![Screenshot_20240812-163934](https://github.com/user-attachments/assets/3deea7d0-fcb9-4f42-9cae-d14f537d5961)
![Screenshot_20240812-163948](https://github.com/user-attachments/assets/3b6b1433-cb91-47c1-ba3c-896aa5386d96)

### Device info
Please complete any of following info that you can. If your issue relates to simulation results being incorrect, this likely isn't necessary.

 - Device: Pixel 6
 - OS: Android 
 - Browser: Chrome
 - Browser version: Chrome 127.0.6533.103

### Additional context
This was the first time accessing the site since I cleared cookies/cache, so was recreating the profiles fresh.

**Comment by dixhuit** [comment]
Good spot, thanks for the bug report. I'll get this regression fixed ASAP.

**Comment by dixhuit** [comment]
Fixed in v0.65.5 (just released).
