### ISSUE TITLE
Add support for `Extra Attacks` weapons

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#109]
Add support for the weapon ability [`Extra Attacks`](https://wahapedia.ru/wh40k10ed/the-rules/core-rules/#Extra-Attacks), this would help simulate factions that have a lot of units with **Extra attack** weapons along with an Army/detachment rule that increases weapon attacks such as the Orks & Blood Angels faction.

My proposal would be to create a new weapon ability that disables any `Increase weapon attacks #` effects only for that weapon, it could be included as an option in the `Disable mechanic effect` or as a new `Special effect` these are just suggestions as i imagine you'll have a better understanding of where this effect would go.

**Comment by dixhuit** [comment]
Took me a while to understand the point of this proposal but I think I follow you now! You raise a good point. So basically the need all stems from this sentence at the end of the `Extra Attacks` rule:

> The number of attacks made with an `Extra Attacks` weapon cannot be modified by other rules, unless that weapon’s name is explicitly specified in that rule.

As it stands, UC _would_ increase the number of attacks that an `Extra Attacks` weapon has if you enable a global modifier or profile ability that has an effect that increases the number of attacks (which is incorrect in many cases).

My suggestion would therefore be:

1. Add a new weapon ability: `EXTRA ATTACKS` - which does nothing but mark a weapon as such (much like `PSYCHIC`). This would likely be an option under "Special" effects.
2. Add a checkbox to the "Increase weapon attacks" effect (defaulting to unchecked) labelled "Apply to weapons with the `EXTRA ATTACKS` ability". This would then allow the user to toggle whether this effect is applied to weapons with that ability or not.
3. On the rare occasion that the above effect does have its checkbox checked, add the following suffix to the end of the resulting modifier description: "(include EXTRA ATTACKS weapons)".

**Comment by korzxd** [comment]
> the need all stems from this sentence at the end of the Extra Attacks rule:
> > The number of attacks made with an Extra Attacks weapon cannot be modified by other rules, unless that weapon’s name is explicitly specified in that rule.

I probably should of led with that 😅.

Your suggestion sounds great. Looking forward to seeing the result, Thanks!
