### ISSUE TITLE
Weapons are not cloning properly

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#110]
### Describe the bug
I have 2 different weapons called `A` and `B`, if i clone `A` and click save it works, then when i clone `B` and click save it overwrites the `A (clone)` weapon i just created.

### To Reproduce
1. Import this profile [Weapon clone bug.txt](https://github.com/user-attachments/files/16735610/Weapon.clone.bug.txt).
2. Go to `Manage Profiles`
3. Go into Edit mode for the `Warboss` profile.
4. Clone the `Big choppa` weapon.
5. Click `Save`.
6. Clone the `Power Klaw` weapon.
7. You can now see in the Background we have the weapon order.
    * Big choppa
    * Power klaw
    * Big choppa (clone)
    * Power klaw (clone)
9. Change the attacks characteristic.
10. Click `Save`.
11. See result. The new weapon order is
    * Big choppa
    * Power klaw
    * Power klaw (clone)  <- This has the changed attacks characteristic, confirming this is the weapon that was overwritten when clicking save.
    * Power klaw (clone)

This still happens even if you do not perform **Step 9**. This step is only taken to keep track of which weapon was overwritten.

### Expected behavior
I would expect the `Big choppa (clone)` not to of been overwritten when clicking save.

**Comment by dixhuit** [comment]
Oh dear, thanks for the bug report. Will take a look ASAP.

**Comment by dixhuit** [comment]
Fixed in 0.65.6 (released).
