### ISSUE TITLE
Add feature to set custom description name for unit ability

### ISSUE THREAD

**Issue by etagimarketing** [dixhuit/unitcrunch-issue-tracker#117]
At the moment, the ability description field is generated automatically. I would really like to see the ability to set the name myself.

![image](https://github.com/user-attachments/assets/fa8d29a8-cd38-4a31-b197-174a9b697247)

**Comment by dixhuit** [comment]
I have plans (https://github.com/dixhuit/unitcrunch-issue-tracker/issues/68) for users to be able to enter their own ability alias, as well as UC providing a handful of reserved aliases as it does now:

![image](https://github.com/user-attachments/assets/b9bcc786-e1c6-468e-9ab7-a09fd341c02f)

But I think that having user editable descriptions would be a mistake. Having UC generate the description provides a consistent way to describe an ability outside of UC that would be rendered useless if anyone could replace the description with any text they want.
