### ISSUE TITLE
"PSYCHIC" weapon support

### ISSUE THREAD

**Issue by dixhuit** [dixhuit/unitcrunch-issue-tracker#2]
Add a weapon ability effect that adds the `PSYCHIC` USR and a condition that tests for its presence.

https://www.reddit.com/r/UnitCrunch/comments/16kjkky/psychic_usr/

> I feel that there are enough weapons and abilities that deal with the Psychic USR for weapons and defensive options to warrant including these tags, especially when oftentimes units with those USRs have that option mixed in with non-psychic weapons that interact differently with a unit's loadout options.
>
> A good example of this is something like a Farseer embedded in a unit of Guardian Defenders shooting at a unit of Necron Warriors in range of a [Canoptek Spyder](https://wahapedia.ru/wh40k10ed/factions/necrons/Canoptek-Spyders)'s Gloom Prism aura; the Warriors would get a 4+++ against the Farseer's Eldritch Storm and Singing Spear / Witchblade attacks, but not against the Guardians' Shuriken Catapults, Heavy Weapons Platform, and Close Combat Weapons, nor the Farseer's Shuriken Pistol.

**Comment by dixhuit** [comment]
Won the Discord vote on 2023/12/08 🥇

**Comment by korzxd** [comment]
I've only had time to test quickly this morning but the interaction with FNP seems to not be working properly.

I've made an attacker profile with 3 weapons:
  * Psychic & disable save
  * Normal & disable save
  * Mortal wounds

I added disable save to match the same conditions as the Mortal wounds weapon for simple comparison.

I've also created a Defender profile with 4 Modifiers:
  * FNP
  * FNP - Psychic only
  * FNP - MW only
  * FNP - Psychic & MW only (only displays as psychic)

Below i've attached screenshots showing the weapon results against the various FNP modifiers.

### No Modifiers
![_0005_Layer-2](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/9692c915-0eb0-48b8-92e3-cdc0501108d1)

### FNP
![_0003_Layer-3](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/17793a15-5d4d-4452-a45c-b71cfd610311)

### FNP - Psychic only
![_0002_Layer-4](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/f9eebfea-1079-41fc-9e3a-44429897b359)

### FNP - MW only
![_0001_Layer-5](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/796c6522-e466-42c3-9506-e767c3295f87)

### FNP - Psychic & MW only
![_0000_Layer-6](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/66ec143c-dbcf-490b-b448-9440b5b7954b)

Heres a screenshot of the modifier for that last one
![_0004_Layer-1](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/15906310/1d98fe33-1c95-4778-88aa-df9c4cf0d99e)

I would've cropped the screengrabs for easy readability but i'm short on time today.

I've also attached an export of both profiles if you wanted to replicate it, hope this helps 👍
[unitcrunch-export-p2 (1).txt](https://github.com/dixhuit/unitcrunch-issue-tracker/files/13683802/unitcrunch-export-p2.1.txt)

**Comment by dixhuit** [comment]
@korzxd Thanks for the feedback. I don't have time to dive into this just yet (I will though!). Can you describe the issue here when you get a minute? Is it just the incorrect description on the 4th FNP modifier or is there more that wrong? Cheers!

**Comment by dixhuit** [comment]
Turns out the modifier description issue highlighted here is a bug that's already in production (regression in v0.59.0). I'm just testing a fix and then will redeploy a preview of 0.60.0.

**Comment by dixhuit** [comment]
Have redeployed the preview of 0.60.0 with a fix for #29.
