### ISSUE TITLE
Import not working as intended

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#35]
**Describe the bug**
Import button in the import overlay menu does nothing when `Add to existing data` is checked. `Replace existing data` still works as intended.

**To Reproduce**
1. Go to `Manage profiles`
2. Click on `Import`
3. Click on `Select file`
4. Choose file
5. Click on `Import`
6. See error

**Expected behavior**
To import.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 120.0.1

**Comment by dixhuit** [comment]
Thanks for this. I have now deployed a hot fix.
