### ISSUE TITLE
Global Modifiers not showing as an option (other than the checkbox ones). Cannot add new ones.

### ISSUE THREAD

**Issue by Malifus** [dixhuit/unitcrunch-issue-tracker#56]
**Describe the bug**
I have no access to adding/using Global Modifers.

**To Reproduce**
Only happening on my PC. Laptop and phone are fine

**Expected behavior**
Have access to adding global modifiers

**Screenshots**
Screenshot added
![Screenshot 2024-02-23 093923](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/161048253/cbeab7c5-5477-40df-9483-4fcea88a44c2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version 121.0.2277.128 (64 bit)

**Comment by dixhuit** [comment]
Thanks for the bug report. I've not seen this before! Would you mind submitting the form at https://www.unitcrunch.com/send-debug-data from your PC please? That will send me enough data to try to recreate the issue at my end so I can work on a fix.

**Comment by Malifus** [comment]
Sent! Thank you for looking into this, love the website!

**Comment by dixhuit** [comment]
Debug data received. Thanks. Will look into this ASAP. Glad you like the site!

**Comment by dixhuit** [comment]
Should be fixed in 0.62.0 which I hope to release tomorrow (Tuesday). I'll leave this issue open _just in case_.

**Comment by dixhuit** [comment]
0.62.0 has been released.

**Comment by Malifus** [comment]
Works perfectly, thank you!

**Comment by dixhuit** [comment]
That's great news :)
