### ISSUE TITLE
Add ANTI-DAEMON support

### ISSUE THREAD

**Issue by raddue** [dixhuit/unitcrunch-issue-tracker#58]
Please help us poor Grey Knight players do math for Draigo into Angron and Magnus!  🗡️

**Comment by dixhuit** [comment]
So it looks like UC is missing some preset weapon abilities for `ANTI-DAEMON *+` but are you aware that you can already create the required weapon abilities yourself?

![image](https://github.com/dixhuit/unitcrunch-issue-tracker/assets/6885065/da46a608-20af-4aac-a05b-ce4dc884d620)

I can add the preset abilities pretty easily so I might even include those in a patch release this week.

**Comment by raddue** [comment]
You know, I **did** know that we could add those customizations, but I never could figure out exactly what roll requirement I needed to select in order to get that to function.  Then again, I never gave it a lot of time, either.  😂

**Comment by dixhuit** [comment]
All done. The following preset weapon abilities will be in 0.62.1 when it's released:

- `ANTI-DAEMON 2+`
- `ANTI-DAEMON 3+`
- `ANTI-DAEMON 4+`

**Comment by dixhuit** [comment]
0.62.1 has now been released.
