### ISSUE TITLE
"No weapons selected" when simulating older Data Exports.

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#80]
### Debug data
Submitted Debug Data.

### Describe the bug
"No weapons selected" appears when using some older profiles in the Crunch window. Only happens when there is one weapon option available.

### To Reproduce
1. Import the [Tau Data Export](https://github.com/korzxd/UnitCrunch-data-exports/blob/main/Tau/T'au-v1.2.txt)
2. Select Vespid Stingwings as the Attacker profile.
4. Select another random profile to sim against.
5. `Incomplete data for simulation No weapons selected.` appears on the sim data.
6. This happens with both the Melee and Ranged weapons

### Device info
 - Device: [PC]
 - OS: [Windows 10]
 - Browser [Chrome]
 - Browser version [125.0.6422.142]

### Additional context
The same thing happens with Darkstrider, Ethereal with there Ranged profiles.
This also occurs with the other Data Exports, such as the Aeldari export when selecting the Guardian Defenders Melee profile.

**Comment by dixhuit** [comment]
Thanks for this, will take a look when i next get a chance.

**Comment by dixhuit** [comment]
This should now be sorted in 0.62.7 (just released). Can you confirm things are working for you now?

**Comment by korzxd** [comment]
I've only just got round to testing this, i've followed the same steps as above and it's still saying `Incomplete data for simulation No weapons selected`.

Also a new bug's appeared, this bug wasn't present in the previous version, after importing the profiles the "New Profile" button's disabled. When switching to the Crunch tab the "Saved Profiles" & "New Profile buttons" are also disabled. I've found refreshing the page fixes this issue.

**Comment by dixhuit** [comment]
Have you tried re-importing the data export file?

**Comment by korzxd** [comment]
Re-importing with "Replace" ticked produces the same outcome, all the "Profile" associated buttons are disabled.

After refreshing the page, those buttons re-enable but when selecting the Vespid stingwing profile is still says Incomplete data for simulation No weapons selected.Incomplete data for simulation No weapons selected.

~~I've found if there are 0 profiles and i import a Data Export then after importing the profiles the "New Profile", "Saved Profiles" & "New Profile buttons" buttons are disabled. If there is at least 1 profile before i import then the buttons do not disable.~~

EDIT: Ignore the last line that's incorrect it happens everytime i import regardless of existing profile count.

**Comment by dixhuit** [comment]
Right, I can now recreate this. Turns out I was importing an older version of your Tau export file which is interesting. I just re-cloned your repo from fresh, imported the latest (1.2) version of the Tau data export and I now see the disabled buttons. Will investigate further...

**Comment by dixhuit** [comment]
OK, try now?
