### ISSUE TITLE
Damage dealt reported exceeds wounds per model of defender

### ISSUE THREAD

**Issue by hhcauldwell** [dixhuit/unitcrunch-issue-tracker#83]
### Debug data
You can send debugging data to help with diagnosing the issue. Just set up a simulation that recreates the issue and then submit the form at: https://www.unitcrunch.com/send-debug-data

### Describe the bug
A weapon that causes more damage than the wound characteristic of a defender model is reporting the total damage dealt by the weapon (overkill) rather than wounds inflicted on the defending model. I believe this results in misleading data.

### Expected behavior
Damage dealt by a weapon should not exceed the wounds remaining of a defending model.

### Device info
Please complete any of following info that you can. If your issue relates to simulation results being incorrect, this likely isn't necessary.

 - Device: [e.g. iPhone6, desktop PC, etc.]
 - OS: [e.g. iOS, Windows 11, etc.]
 - Browser [e.g. Chrome, Safari, etc.]
 - Browser version [e.g. 22]

### Additional context
Add any other context about the issue.

**Comment by dixhuit** [comment]
Hi there, thanks for the bug report. I've no way to recreate what you're seeing, please could you send me some debug data as per the prompt at the top of the issue template?

> You can send debugging data to help with diagnosing the issue. Just set up a simulation that recreates the issue and then submit the form at: https://www.unitcrunch.com/send-debug-data

Failing that, maybe you could send some screenshots (debug data is nearly always more useful though)?

**Comment by dixhuit** [comment]
Am gonna close & add this issue to the 0.64.0 milestone as displaying overkill information is being removed in 0.64.0 anyway (which sounds like it might address whatever the specifics of this issue are - I don't know because I still don't have enough information).
