### ISSUE TITLE
Support `(MELEE|RANGED)` suffix on certain reserved modifier aliases. Add new preset modifiers that use this.

### ISSUE THREAD

**Issue by korzxd** [dixhuit/unitcrunch-issue-tracker#98]
Add Melee only and Ranged only Aliases for:
* Devastating wounds
* Lethal Hits
* Sustained Hits

I found instances of Anti-X melee/ranged only as well, but there were so little occurrences that i felt it unnecessary to include them.

This has only occurred to me now as I'm updating the Data Exports and I've found a lot of Devastating Wounds melee/ranged only that needed to be updated with the new Devastating Wounds change as they were not an alias.

**Comment by dixhuit** [comment]
> Add Melee only and Ranged only Aliases

Do you mean presets?

**Comment by korzxd** [comment]
Yeah that's what I meant 😅

**Comment by dixhuit** [comment]
Could you share some example datasheets for this? I need to be careful here as strictly speaking, something like "Devastating wounds" doesn't have an attack type condition (Melee | Ranged). I'm willing to go there if needed but I'm interested to see how it's done across various datasheets first. Cheers!

**Comment by korzxd** [comment]
> > Add Melee only and Ranged only Aliases

> Do you mean presets?

Sorry i must've been busy when i replied to this, wouldn't it have to be Presets along with an Alias?
Unless i'm misunderstanding how it works, but without the Alias tag i would still have to re-visit and edit these abilities if games workshop make another change to the ruling?

**Comment by korzxd** [comment]
Also list of known examples from a few Factions.

### Devastating Wounds
* [Autarch](https://wahapedia.ru/wh40k10ed/factions/aeldari/Autarch)
* [Autarch Wayleaper](https://wahapedia.ru/wh40k10ed/factions/aeldari/Autarch-Wayleaper)
* [Karandras](https://wahapedia.ru/wh40k10ed/factions/aeldari/Karandras)
* [Troupe Master](https://wahapedia.ru/wh40k10ed/factions/aeldari/Troupe-Master)
* [Striking Scorpions](https://wahapedia.ru/wh40k10ed/factions/aeldari/Striking-Scorpions)
* [Captain](https://wahapedia.ru/wh40k10ed/factions/space-marines/Captain)
* [Chaplain On Bike](https://wahapedia.ru/wh40k10ed/factions/space-marines/Chaplain-On-Bike)
* [Eliminator Squad](https://wahapedia.ru/wh40k10ed/factions/space-marines/Eliminator-Squad)
* [Skulltaker](https://wahapedia.ru/wh40k10ed/factions/chaos-daemons/Skulltaker)
* [Marshal](https://wahapedia.ru/wh40k10ed/factions/space-marines/Marshal)
* [Astorath](https://wahapedia.ru/wh40k10ed/factions/space-marines/Astorath)

### Sustained Hits X
* [Cadian Castellan](https://wahapedia.ru/wh40k10ed/factions/astra-militarum/Cadian-Castellan)
* [Militarum Tempestus Command Squad](https://wahapedia.ru/wh40k10ed/factions/astra-militarum/Militarum-Tempestus-Command-Squad)
* [Regimental Preacher](https://wahapedia.ru/wh40k10ed/factions/astra-militarum/datasheets.html#Regimental-Preacher)
* [Changecaster](https://wahapedia.ru/wh40k10ed/factions/chaos-daemons/Changecaster)
* [Spoilpox Scrivener](https://wahapedia.ru/wh40k10ed/factions/chaos-daemons/Spoilpox-Scrivener)
* [Tormentbringer On Exalted Seeker Chariot](https://wahapedia.ru/wh40k10ed/factions/chaos-daemons/Tormentbringer-On-Exalted-Seeker-Chariot)
* [Cerastus Knight Castigator](https://wahapedia.ru/wh40k10ed/factions/imperial-knights/Cerastus-Knight-Castigator)
* [Kroot Flesh Shaper](https://wahapedia.ru/wh40k10ed/factions/t-au-empire/Kroot-Flesh-Shaper)
* [Canis Wolfborn](https://wahapedia.ru/wh40k10ed/factions/space-marines/Canis-Wolfborn)

### Lethal Hits X
* [Shroud Runners](https://wahapedia.ru/wh40k10ed/factions/aeldari/Shroud-Runners)
* [Iron Hand Straken](https://wahapedia.ru/wh40k10ed/factions/astra-militarum/Iron-Hand-Straken)
* [Fateskimmer](https://wahapedia.ru/wh40k10ed/factions/chaos-daemons/Fateskimmer)
* [Lemartes](https://wahapedia.ru/wh40k10ed/factions/space-marines/Lemartes)
* [Vanguard Veteran Squad With Jump Packs](https://wahapedia.ru/wh40k10ed/factions/space-marines/Vanguard-Veteran-Squad-With-Jump-Packs)

**Comment by korzxd** [comment]
There's probably no chance of Sustained Hits/Lethal Hits changing but you never know with games workshop, so i thought i'd include the examples.

**Comment by dixhuit** [comment]
@korzxd This is underway and will support a `(MELEE)`|`(RANGED)` suffix for the following reserved aliases:

* `ANTI-*`
* `DEV WOUNDS`
* `LETHAL HITS`
* `SUSTAINED HITS`

I will create additional new melee & ranged presets for the all of the above bar `ANTI-*`. What do you reckon for `SUSTAINED HITS` - just `SUSTAINED HITS 1` & `SUSTAINED HITS 2`?

**Comment by dixhuit** [comment]
@korzxd Do you have a UC export that already uses modifiers that these new aliases would apply to? If so could you share it? It would be really useful for testing the modifier migration that I'm writing.

**Comment by korzxd** [comment]
> What do you reckon for SUSTAINED HITS - just SUSTAINED HITS 1 & SUSTAINED HITS 2?

SUSTAINED HITS 1 will probably suffice, i don't recall seeing any other instance where it's greater than 1.

> Do you have a UC export that already uses modifiers that these new aliases would apply to?

Yeah sure, [Astra-Militarum-v1.1.txt](https://github.com/user-attachments/files/16378080/Astra-Militarum-v1.1.txt):
* ‘Iron Hand’ Straken - Lethal Hits (melee only)
* Cadian Castellan - Sustained Hits (ranged only)

[Tau-v1.2](https://github.com/user-attachments/files/16378127/Tau-v1.2.txt)
* Kroot Flesh Shaper - Sustained Hits (melee only)

I would've suggested the Shroud runners for Lethal Hits (ranged only) but it appears i forgot to apply the ranged condition in that one.

I don't have any examples of Devastating wounds as all of the profiles that had a melee/ranged only condition would still be using the old method `Critical wound : disable save (inc. invuln) (melee only)` rather than the new `Critical wound : mortal wounds equal to weapon damage (attack sequence ends) (no spill over) (melee only) (if attacker)`.

**Comment by dixhuit** [comment]
Nice one, thanks.

> I don't have any examples of Devastating wounds as all of the profiles that had a melee/ranged only condition would still be using the old method Critical wound : disable save (inc. invuln) (melee only) rather than the new Critical wound : mortal wounds equal to weapon damage (attack sequence ends) (no spill over) (melee only) (if attacker).

Troupe Master?

**Comment by korzxd** [comment]
> Troupe Master?

If you don't mind it being a v0.64 export you could use [Aeldari-v1.2.txt](https://github.com/user-attachments/files/16380665/Aeldari-v1.2.txt) from issue #101.

The current release version [Aeldari-v1.1.txt](https://github.com/user-attachments/files/16380710/Aeldari-v1.1.txt) made with v0.62 still uses the `Critical wound : disable save (inc. invuln) (melee only) ` method.

**Comment by dixhuit** [comment]
v0.64 export is fine, thanks!
